name: Build Android arm64

on:
  workflow_dispatch: # manually triggered

env:
  ANDROID_TARGET_SDK_VERSION: 27
  TARGET_ARCH: arm64

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install build utils
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-multilib g++-multilib

    - name: Build
      run: |
        ./tools/android_build.sh $ANDROID_NDK_HOME $ANDROID_TARGET_SDK_VERSION $TARGET_ARCH
        rm -rf ./out_android/libnode

    - uses: actions/upload-artifact@v4
      with:
        name: node-android-${{ env.TARGET_ARCH }}
        path: out_android
